mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^',include('mainpage.urls')),
    url(r'^alert/kuuu',include('alert.urls')),
    url(r'^buyAndSell/',include('buyAndSell.urls')),
    url(r'^orderAndTrade/',include('orderAndTrade.urls')),
    url(r'^chart/',include('chart.urls')),
    url(r'^tickers/',include('tickers.urls')),
    url(r'^titleCurrencie/',include('titleCurrencie.urls')),
    url(r'^landpage/', include('landpage.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/tickers/urls.py
from django.conf.urls import url

from . import views
from django.views.generic import TemplateView



app_name = 'tickers'
urlpatterns = [   
    url(r'^$', views.index, name='index'),
]

mysite/user/urls.py
from django.conf.urls import url
from django.contrib.auth.models import User

from . import views
from django.views.generic import TemplateView



app_name = 'user'
urlpatterns = [   
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^deposit/$', views.deposit, name='deposit'),
    url(r'^withdraw/$', views.withdraw, name='withdraw'),
]

mysite/tickers/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render
from functools import reduce
from orderAndTrade.views import get_history

# Create your views here.

def index(request):
    data = get_history()
    first_price = float(data[-1].get('bidprice'))
    price = float(data[0].get('bidprice'))
    volume = reduce((lambda x, y: x + float(y.get('amount'))), data, 0)
    change = float((price - first_price) / first_price)
    result = {
        "code": 200,
        "data": [
            {
                'symbol': "btc", 'price': price, 'change': change, 'volume': volume
            }
        ]
    }
    return HttpResponse(json.dumps(result), content_type="application/json")

mysite/tickers/templates/tickers/block.html
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            <i class="fa fa-line-chart"><b> Tickers</b></i></h3> 
    </div>
    <div class="panel-body">
        <div id="ticker-chart"></div>
    </div>
</div>

<script>
    $(function() {
        const drawChart = (result) => {
            if (result.code === 200) {
                $("#ticker-chart").shieldGrid({
                    dataSource: {
                        data: result.data
                    },
                    sorting: {
                        multiple: true
                    },
                    rowHover: true,
                    paging: false,
                    columns: [
                        { field: "symbol", width: "50px", title: "<small>Sym</small>" },
                        { field: "last", title: "Last" },
                        { field: "percent", title: "24H", format: "{0}%" },
                        { field: "volume", title: "Volume" },
                    ]
                });
            }
        }
        const refreshGird = (result) => {
            if (result.code === 200) {
                const grid = $("#ticker-chart").swidget();
                const initialOptions = grid.initialOptions;
                initialOptions.dataSource = {
                    data: result.data 
                };
                grid.refresh(initialOptions);
            }
        }
        const getData = (callback) => $.get("{% url "tickers:index" %}", callback)

        setInterval(getData, 1000 * 60, refreshGird)
        getData(drawChart)
    })
</script>