mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^',include('mainpage.urls')),
    url(r'^alert/kuuu',include('alert.urls')),
    url(r'^buyAndSell/',include('buyAndSell.urls')),
    url(r'^orderAndTrade/',include('orderAndTrade.urls')),
    url(r'^chart/',include('chart.urls')),
    url(r'^tickers/',include('tickers.urls')),
    url(r'^titleCurrencie/',include('titleCurrencie.urls')),
    url(r'^landpage/', include('landpage.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/user/urls.py
from django.conf.urls import url
from django.contrib.auth.models import User

from . import views
from django.views.generic import TemplateView



app_name = 'user'
urlpatterns = [   
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^deposit/$', views.deposit, name='deposit'),
    url(r'^withdraw/$', views.withdraw, name='withdraw'),
]

mysite/user/views.py
from django.shortcuts import render

from datetime import datetime  
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import HttpResponse, HttpResponseRedirect

from mainpage.models import Account
# Create your views here.

def index(request):
    if request.user.is_authenticated: 
        account = Account.objects.get(user_id=request.user)
        return render(request, 'user/index.html', { 'balance': account.total_buy_sell_deposit_withdraw })
    return HttpResponseRedirect('/user/login')


def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.create_user(username, '', password)
        user.email = email
        user.save()
        user = auth.authenticate(username=username, password=password)
        account = Account.objects.create(user_id=user, creation_location="Taipei", last_password_modified_time=datetime.now(), last_login_ip="127.0.0.1", last_login_ip_location="Taipei", total_buy_sell_deposit_withdraw=0, phone_number="0912345678", national_id_proof="fake", first_name=username, last_name="Bithundi")
        account.save()
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/user')
        else:
            return HttpResponseRedirect('/user/login')
    else:
        if request.user.is_authenticated: 
            return HttpResponseRedirect('/user')
        return render(request, 'user/register.html')


def login(request):
    if request.user.is_authenticated: 
        return HttpResponseRedirect('/user')

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    
    user = auth.authenticate(username=username, password=password)

    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/user')
    else:
        return render(request, 'user/login.html') 


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/user/login')

def setting(request):
    return render(request, 'user/setting.html')

def withdraw(request):
    account = Account.objects.get(user_id=request.user)
    account.total_buy_sell_deposit_withdraw -= int(request.POST.get("amount"))
    account.save()
    return HttpResponseRedirect('/user')

def deposit(request):
    account = Account.objects.get(user_id=request.user)
    account.total_buy_sell_deposit_withdraw += int(request.POST.get("amount"))
    account.save()
    return HttpResponseRedirect('/user')

mysite/user/templates/user/base.html
{% extends "mysite/base.html" %}

{% block status %}
{% include "user/status.html" %}
{% endblock %}

{% block body %}
{{ block.super }}
{% endblock %}

mysite/user/templates/user/deposit.html
<form action="{% url "user:deposit" %}" method="POST">
    {% csrf_token %}
    <div class="row text-center">
        <h2>Deposit</h2>
    </div>
    <div class="row">
        <label for="amount" class="col-md-2">
            Amount:
        </label>
        <div class="col-md-9">
            <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount of USD" required>
        </div>
        <div class="col-md-1">
            <i class="fa fa-lock fa-2x"></i>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <label>
                <input type="checkbox" required> I hereby accept the terms and conditions for using this site</label>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-info">
                Deposit
            </button>
        </div>
    </div>
</form>

mysite/user/templates/user/index.html
{% extends "user/base.html" %}

{% block title %} Profile {% endblock %}

{% block body %}
{{ block.super }}
<h1>Current Account Balance: {{balance}}</h1>
{% include "user/withdraw.html" %}
{% include "user/deposit.html" %}
<a href="/">Go to Dashboard</a>
{% endblock %}

mysite/user/templates/user/login.html
{% extends "user/base.html" %}

{% block title %} Login {% endblock %}

{% block body %}
{{ block.super }}
<form action="" method="post">
    {% csrf_token %}
    <div class="row text-center">
        <h2>Login User</h2>
    </div>
    <div class="row">
        <label for="username" class="col-md-2">
            Username:
        </label>
        <div class="col-md-9">
            <input type="text" class="form-control" id="username" name="username" placeholder="Username for login" required>
        </div>
        <div class="col-md-1">
            <i class="fa fa-lock fa-2x"></i>
        </div>
    </div>
    <div class="row">
        <label for="password" class="col-md-2">
            Password:
        </label>
        <div class="col-md-9">
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
        </div>
        <div class="col-md-1">
            <i class="fa fa-lock fa-2x"></i>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <label>
                <input type="checkbox"> Remember Login Info</label>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-info">
                Login
            </button>
        </div>
    </div>
</form>
{% endblock %}

mysite/user/templates/user/register.html
{% extends "user/base.html" %}

{% block title %} Register {% endblock %}

{% block body %}
{{ block.super }}
<div id="register">
    <form action="{% url "user:register" %}" method="POST">
        {% csrf_token %}
        <div class="row text-center">
            <h2>New User</h2>
        </div>
        <div class="row">
            <label for="username" class="col-md-2">
                Username:
            </label>
            <div class="col-md-9">
                <input type="text" class="form-control" id="username" name="username" placeholder="Username for login" required>
            </div>
            <div class="col-md-1">
                <i class="fa fa-lock fa-2x"></i>
            </div>
        </div>
        <div class="row">
            <label for="email" class="col-md-2">
                Email:
            </label>
            <div class="col-md-9">
                <input type="email" class="form-control" id="email" name="email" placeholder="Email for further contact" required>
            </div>
            <div class="col-md-1">
                <i class="fa fa-lock fa-2x"></i>
            </div>
        </div>
        <div class="row">
            <label for="password" class="col-md-2">
                Password:
            </label>
            <div class="col-md-9">
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
                <p class="help-block">
                    Min: 6 characters (Alphanumeric only)
                </p>
            </div>
            <div class="col-md-1">
                <i class="fa fa-lock fa-2x"></i>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <label>
                    <input type="checkbox" required> I hereby accept the terms and conditions for using this site</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <button type="submit" class="btn btn-info">
                    Register
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mysite/user/templates/user/setting.html
{% extends "user/base.html" %}

{% block title %} Setting {% endblock %}

{% block body %}
{{ block.super }}
Not yet implemented
{% endblock %}

mysite/user/templates/user/status.html
<li>
    {% if request.get_full_path == "/user/login/" %}
    <a href="{% url "user:register" %}">Register</a>
    {% elif request.user.is_authenticated %}
    <a href="{% url "user:logout" %}">Logout</a>
    {% else %}
    <a href="{% url "user:login" %}">Login</a>
    {% endif %}
    <!-- {% if request.user.is_authenticated %}
    <a href="{% url "user:logout" %}">Logout</a>
    {% else %}
    <a href="{% url "user:login" %}">Login</a>
    {% endif %} -->
</li>

mysite/user/templates/user/withdraw.html
<form action="{% url "user:withdraw" %}" method="POST">
    {% csrf_token %}
    <div class="row text-center">
        <h2>Withdraw</h2>
    </div>
    <div class="row">
        <label for="amount" class="col-md-2">
            Amount:
        </label>
        <div class="col-md-9">
            <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount" required>
        </div>
        <div class="col-md-1">
            <i class="fa fa-lock fa-2x"></i>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <label>
                <input type="checkbox" required> I hereby accept the terms and conditions for using this site</label>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <button type="submit" class="btn btn-info">
                Withdraw
            </button>
        </div>
    </div>
</form>